name: "Bump Version"

on:
  push:
    branches:
      - "master"

  pull_request:
    types:
      - "closed"
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
