name: "Apply Versioning"

on:
  push:
    branches:
      - "master"

jobs:
  apply_versioning:
    runs-on: "ubuntu-22.04"
    
    steps:
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          debug: true
